### ISSUE TITLE
listenAsync - don't work polling

### ISSUE THREAD

**Issue by ParkFramework** [m6w6/ext-pq#11]
```php

$db = new pq\Connection($dsn);

$db->listenAsync('name', function($name, $message)
{
	echo $message;
});

$r = [$db->socket];
$w = $e = null;

while(stream_select($r, $w, $e, 10))
{
	$db->poll();
}

```
Next for 10 seconds - psql:
```sql
NOTIFY name, 'Hello World!';
```

PHP script callback notification not called, if use `$db->listen(...)` then everything works.

**Comment by m6w6** [comment]
PostgreSQL notifications don't work that way.

1. See https://mdref.m6w6.name/pq/Connection/:%20Asynchronous%20Usage for how to properly perform asynchronous operations
1. You have to fetch the result of the pq\Connection::listenAsync() with pq\Connection::getResult()
1. PostgreSQL notifications do not arrive out of band, they are received while performing other queries

HTH

**Comment by m6w6** [comment]
Here's a working example, but I'm not sure how applicable it is to real world situations:

```php
$c = new pq\Connection;
$x = false;
$c->listenAsync('name', function($name, $message) use(&$x) {
		$x = true;
		echo $message;
});
do {
  while ($c->busy) {
    $r = array($c->socket);
    $w = $e = null;
    if (stream_select($r, $w, $e, 10)) {
      $c->poll();
    }
  }
} while (($c->getResult() && $c->execAsync("")) || !$x);
```

**Comment by ParkFramework** [comment]
Ok, thank.

**Comment by ParkFramework** [comment]
Ok.
Block time `listen()` and `notify()` is very small, so it's best to use them without `async`.

Tthank.
