### ISSUE TITLE
How to get detail error code?

### ISSUE THREAD

**Issue by ParkFramework** [m6w6/ext-pq#14]
We need to know specifically error code, to create specific exception classes.

The documents have a table of detailed error codes:
http://www.postgresql.org/docs/current/static/errcodes-appendix.html

How to get them in `pq\Result`?

Thank.

**Comment by m6w6** [comment]
Check the `sqlstate` property of `pq\Exception\DomainException`:
https://mdref.m6w6.name/pq/Exception/DomainException#$sqlstate

**Comment by m6w6** [comment]
Oh, from pq\Result? Let me check :)

**Comment by m6w6** [comment]
Looks like we're missing the complete `PQresultErrorField()` API :-/

**Comment by m6w6** [comment]
How about a public (readonly) property `pq\Result::$diag` which returns

```
array(
  "severity" => "ERROR",
  "sqlstate" => "A00A00",
  "message_primary" => "...",
  ...
)
```

?

**Comment by m6w6** [comment]
Basically everything that's available from PQresultErrorField: http://www.postgresql.org/docs/current/static/libpq-exec.html#LIBPQ-PQRESULTERRORFIELD

**Comment by ParkFramework** [comment]
Great, thank you!
We are waiting for the new version :)
