### ISSUE TITLE
Restore listeners and statements, after Connection::reset

### ISSUE THREAD

**Issue by ParkFramework** [m6w6/ext-pq#15]
We plan to implement in the application layers, restore `listeners` and `statements`, after `Connection::reset`.

Or perhaps it is better if it is implemented in `ext-pq`?

**Comment by m6w6** [comment]
I think ext-pq should do this through `PGEventConnReset` handling. We're providing facilities for listeners and prepared statements, so we should also handle availability of them after a connection reset (which is not always user-induced).

**Comment by ParkFramework** [comment]
After `resetAsync` or remote event `reset` not fire

**Comment by m6w6** [comment]
> After resetAsync or remote event reset not fire

Can you elaborate? I didn't understand that sentence (especially the occurrence of "remote").

**Comment by ParkFramework** [comment]
> Can you elaborate? I didn't understand that sentence (especially the occurrence of "remote").

Sorry
I mean - remote disconnect

**Comment by m6w6** [comment]
Why should the restore logic not fire when a remote disconnect happens?

**Comment by ParkFramework** [comment]
> Why should the restore logic not fire when a remote disconnect happens?

```php

$connection->on(pq\Connection::EVENT_RESET, function() {
   // never executed, after resetAsync() or remote disconnect PostgreSQL server
});
```

**Comment by m6w6** [comment]
Probably, let me check!

Thank you.

**Comment by m6w6** [comment]
Seems to work here. Keep in mind you have to use the first method presented [here](https://mdref.m6w6.name/pq/Connection/:%20Asynchronous%20Usage#Complete.asynchronous.operation:) to complete async connect/reset.

```php
$c = new pq\Connection(PQ_DSN);

$c->on(pq\Connection::EVENT_RESET, function($conn) {
	var_dump($conn);
});

$c->resetAsync();

// wait until the stream becomes writable
$w = array($c->socket);
$r = $e = null;

if (stream_select($r, $w, $e, null)) {

	// loop until the connection is established
	while (true) {

		switch ($c->poll()) {

			case pq\Connection::POLLING_READING:
				// we should wait for the stream to be read-ready
				$r = array($c->socket);
				stream_select($r, $w, $e, NULL);
				break;

			case pq\Connection::POLLING_WRITING:
				// we should wait for the stream to be write-ready
				$w = array($c->socket);
				$r = $e = null;
				stream_select($r, $w, $e, null);
				break;

			case pq\Connection::POLLING_FAILED:
				printf("Connection failed: %s\n", $c->errorMessage);
				break 2;

			case pq\Connection::POLLING_OK:
				printf("Connection completed\n");
				break 2;
		}
	}
}
```

**Comment by ParkFramework** [comment]
> Seems to work here. Keep in mind you have to use the first method presented here to complete async connect/reset.

Yes, is work.
Problem was in my code, not your bug, sorry.
