### ISSUE TITLE
Failed test with Postgresql < 9.3

### ISSUE THREAD

**Issue by remicollet** [m6w6/ext-pq#19]
Only because of missing entries in "diag"

Version 1.1.1 and 2.1.1:

```
async exec [tests/async003.phpt]
async exec params [tests/async004.phpt]
async prepared statement [tests/async005.phpt]
async unbuffered exec [tests/async006.phpt]
cancel [tests/cancel001.phpt]
```

**Comment by ParkFramework** [comment]
Maybe it will be easier to give up the old versions, make the version requirement  Postgresql >= 9.3 (or 9.4)

**Comment by remicollet** [comment]
@ParkFramework 9.2 is the version available in RHEL / CentOS 7 (a quite common distro)

**Comment by DaveRandom** [comment]
@m6w6 how would you feel about ensuring the array format is always the same by putting dummy `NULL`s in for fields that an older pq doesn't provide? Feels like a cleaner solution to me than branching/skipping tests on pq version, esp. as this is basically what userland would end up having to do as well.

**Comment by m6w6** [comment]
Sounds like a good plan, actually!

**Comment by remicollet** [comment]
@m6w6 using, for each constant
```
#ifndef PG_DIAG_SCHEMA_NAME
#define PG_DIAG_SCHEMA_NAME 's'
#endif
```

From a quick check into the sources, the call to PQresultErrorField will return NULL for unkown case.
Could be a simple way.
