### ISSUE TITLE
Batch mode and query pipelining for PostgreSQL 9.6

### ISSUE THREAD

**Issue by ParkFramework** [m6w6/ext-pq#22]
Hi.

I read an interesting article, all advise
http://blog.2ndquadrant.com/postgresql-latency-pipelining-batching/

This is a good solution of the problem of [queuing queries](https://github.com/m6w6/ext-pq/issues/10) for PostgreSQL 9.6

[Docs](http://2ndquadrant.github.io/postgres/libpq-batch-mode.html)
[Examples](https://github.com/2ndQuadrant/postgres/blob/dev/libpq-async-batch/src/test/examples/testlibpqbatch.c)

What do you think about it?
Thank.

**Comment by m6w6** [comment]
Looks like we should add support for it!

**Comment by ParkFramework** [comment]
> Looks like we should add support for it!

Yes, if implemented to PostgreSQL 9.6

**Comment by m6w6** [comment]
Looks like it did not land in mainline yet (9.6).

**Comment by ParkFramework** [comment]
Yes, it is possible in a future version will.
