### ISSUE TITLE
PHP 7.1.11 core dump

### ISSUE THREAD

**Issue by sm2017** [m6w6/ext-pq#27]
Hello

`escapeBytea` is not compatible with php 7.1.11 , When I execute it php exits with `Segmentation fault`

```php
$c = new pq\Connection('dbname=postgres host=127.0.0.1 port=5432 user=postgres');
var_dump($c->escapeBytea('test'));
```

**Comment by sm2017** [comment]
@m6w6 reply please

**Comment by m6w6** [comment]
Keep cool, we have Christmas holidays over here.



Am 06.01.2018 17:55 schrieb "sm2017" <notifications@github.com>:

**Comment by sm2017** [comment]
@m6w6 Thanks a lot , Can you please release a PECL version?

**Comment by m6w6** [comment]
The build is green now, expect a release tomorrow.

Thanks for the report!
