### ISSUE TITLE
Failed to acquire cancel (invalid socket)

### ISSUE THREAD

**Issue by sm2017** [m6w6/ext-pq#29]
What is exactly the following error?

>Failed to acquire cancel (invalid socket)

Sometime I get it 

```php
<?
$cancel = new Cancel($this->_pgConnection);
$cancel->cancel();
```

**Comment by m6w6** [comment]
The connection is already broken, AFAICT.

https://www.postgresql.org/docs/current/static/libpq-cancel.html
