### ISSUE TITLE
Any chance for a new release?

### ISSUE THREAD

**Issue by dzuelke** [m6w6/ext-pq#32]
The current version is incompatible with PHP 7.3. A new release with e00dd6db695d2d0f0937e8bc250df7640f78602f included would be great!

**Comment by docteurklein** [comment]
I'd love that too! any idea how to build from a specific commit using pecl in the meantime?

**Comment by m6w6** [comment]
Sorry & thanks for the heads up.

I'll tag the release after travis will have turned green.

**Comment by dzuelke** [comment]
Thanks a bunch @m6w6 :)
