### ISSUE TITLE
Stub does not provide types of @var in docblock for pq\Connection::$socket and pq\LOB::$stream

### ISSUE THREAD

**Issue by DemoniacDeath** [m6w6/ext-pq#39]
The stub file provided as `pq.stub.php` on [PECL page](https://pecl.php.net/package/pq) and as `pq.php` in [JetBrains' stubs repo](https://github.com/JetBrains/phpstorm-stubs/blob/master/pq/pq.php) is missing type after `@var` tags in `pq\Connection::$socket` and `pq\LOB::$stream`
```
	/**
	 * The server socket resource.
	 *
	 * @public
	 * @readonly
	 * @var
	 */
	public $socket;
...
	/**
	 * The stream connected to the *large object*.
	 *
	 * @public
	 * @readonly
	 * @var
	 */
	public $stream;
```

I think it should rather be
```
	/**
	 * The server socket resource.
	 *
	 * @public
	 * @readonly
	 * @var resource
	 */
	public $socket;
...
	/**
	 * The stream connected to the *large object*.
	 *
	 * @public
	 * @readonly
	 * @var resource
	 */
	public $stream;
```

based on documentation of these classes.

The problem is that when I'm trying to parse phpstorm-stubs using [phpdocumentor/reflection-docblock](https://github.com/phpDocumentor/ReflectionDocBlock) this ends up being the only stub that gives me a problem because of `InvalidTag`.
What I actually trying to acomplish is to resurrect php-language-server which indexes stubs from JetBrains' repo and after updating to the latest reflection-docblock this is the only problem I am facing atm. I can make a workaround by assuming `mixed` type in this case, but it would be great if the stubs could be updated. I don't know how the `pq.stub.php` file from PECL page was generated so if someone could point me in that direction I could provide a MR

**Comment by m6w6** [comment]
Thanks!

Fixed in https://github.com/mdref/mdref-pq/commit/899fe673bfc2b69e81c009073d6743b2e400f745
