### ISSUE TITLE
ext-pq depends on raphf, but raphf last release is 4 years ago

### ISSUE THREAD

**Issue by FractalizeR** [m6w6/ext-pq#45]
Is that ok?

**Comment by m6w6** [comment]
Yep. RAPHF, only provides an internal API to manage (persistent) resources, and v2 works for PHP-7 **and greater**!

Thanks for the heads up, though; I updated the docs: https://github.com/mdref/mdref-raphf/commit/2ef1211b21f0399f91e6d2d897a925402c4c3f52
