### ISSUE TITLE
Persistent connect,  query "RESET ALL" always executed at the end of the script?

### ISSUE THREAD

**Issue by ParkFramework** [m6w6/ext-pq#5]
Perhaps to make conditions if a new session uses the same `$application_name` not to `RESET ALL`?

**Comment by m6w6** [comment]
Yes, "RESET ALL" is always executed when a persistent connection is retired.

I don't think there's any value not to do it, rather, it might be dangerous not to do.

You would do your "SET ..." queries anyway after obtaining a connection.

What's your use-case?

**Comment by ParkFramework** [comment]
Yes, it works reliably.

I was thinking how to optimize work script, each time to do a SET, is worth the extra time and you can not see last `query` (he always `RESET ALL`).

Ok, it is not critical.

**Comment by m6w6** [comment]
I see that it comes with a few drawbacks, but on the other hand it would be quite dangerous not to reset a persistent connection.

**Comment by m6w6** [comment]
Ah, one last thing, please make a PR to add your name to https://github.com/m6w6/ext-pq/blob/master/THANKS !
