### ISSUE TITLE
FETCH_CLASS

### ISSUE THREAD

**Issue by ParkFramework** [m6w6/ext-pq#7]
I did not find in the documentation option fetch `FETCH_CLASS`
Like `PDO::FETCH_CLASS`
http://php.net/manual/en/pdo.constants.php

You want to add this option, or we write the implementation in PHP userland?
Thank.

**Comment by m6w6** [comment]
Sorry, this feature was deliberately left out, because the can of worms it opens: do we call the ctor before or after we set the properties, do we even call the ctor at all? Et cetera, et cetera... :)

See also: https://bugs.php.net/search.php?cmd=display&search_for=FETCH_CLASS&x=0&y=0&status=All

**Comment by ParkFramework** [comment]
Ok.

**Comment by m6w6** [comment]
Anyway, thanks for your suggestion!
