### ISSUE TITLE
pq\Connection::listen - require polling?

### ISSUE THREAD

**Issue by ParkFramework** [m6w6/ext-pq#8]
This does not work:
```php
$conn1 = new pq\Connection($dsn);
$conn1->listen("queue", function($channel, $message, $backend_pid) {
	echo $message;
});

$conn2 = new pq\Connection($dsn);
$conn2->notify("queue", "Hello World!");
```
That's work, if send any query `$conn1->exec(';')` after `$conn2->notify`
```php
$conn1 = new pq\Connection($dsn);
$conn1->listen("queue", function($channel, $message, $backend_pid) {
	echo $message;
});

$conn2 = new pq\Connection($dsn);
$conn2->notify("queue", "Hello World!");

$conn1->exec(';');
```

This is a bug or so conceived?
I need async event-loop without polling, like `pub/sub` in Redis :)

**Comment by m6w6** [comment]
Yes, unfortunately, this is how it works in PostgreSQL, you have to perform some action to get notified.

Thanks.

EDIT: Actually I just read the last paragraph again in the [lipq docs](http://www.postgresql.org/docs/current/static/libpq-notify.html): 

> A better way to check for NOTIFY messages when you have no useful commands to execute is to call PQconsumeInput, then check PQnotifies. You can use select() to wait for data to arrive from the server, thereby using no CPU power unless there is something to do. (See PQsocket to obtain the file descriptor number to use with select().) Note that this will work OK whether you submit commands with PQsendQuery/PQgetResult or simply use PQexec. You should, however, remember to check PQnotifies after each PQgetResult or PQexec, to see if any notifications came in during the processing of the command.

That would mean we have to select() on Connection::$socket and use Connection::poll(). I gotta have to check, how that works out!

Thanks.

**Comment by m6w6** [comment]
So e.g.

```php
$r[] = $conn1->socket;
$w = $e = null;

while (stream_select($r, $w, $e, 1)) {
	$conn1->poll();
}
```

**Comment by ParkFramework** [comment]
I understand, but `stream_select()` blocks PHP script.
We need to run at the time of polling of our inactivity event-loop `swoole_server`
I'll try to add a connection to a common event-loop
https://rawgit.com/tchiotludo/swoole-ide-helper/english/docs/classes/swoole_server.html#method_bind

P.S.
We need a notification to PHP client for invalidate clche DB, this is a very interesting task :)

**Comment by m6w6** [comment]
Hey! `stream_select` does not necessarily block, set the timeout to 0 (zero) to let it return immediately:

```php
$r = [$conn->socket];
if (stream_select($r,$w,$e,0)) {
    $conn->poll();
}
```
Hope this helps!

**Comment by ParkFramework** [comment]
Yes I know.

Zero timeout is useful if the message has come, new messages in real time would like to have in the common event-loop `swoole_server`.

Anyway, thanks.
